# Generated by Django 4.0.2 on 2022-02-19 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteczka_app', '0002_book'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='year',
            field=models.IntegerField(),
        ),
    ]
